<a href="https://colab.research.google.com/github/Vishwas02mehta/ML-assignments3rdyear102317022/blob/main/machinefile1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: Questions on Basic NumPy Array
(a) Reverse the NumPy array: arr = (b) Flatten the NumPy arr: array1 = NumPy in-built methods
(c) Compare the following numpy arrays:
np.array([1, 2, 3, 6, 4, 5])
np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array([1,2,3,4,5,1,2,1,1,1])
np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = ii. y = (e) For the array gfg = i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise
np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix
(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr2 = np.flip(arr)
arr2


array([6, 5, 4, 3, 2, 1])

In [ ]:
arr3 = np.array([[1,2,3] , [4,5,6] , [6,7,8]])
flattenedarr = arr3.flatten()
flattenedarr


array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [ ]:
arr4 = np.array([[1,2] , [3,4]])
arr5 = np.array([[1,2] , [3,4]])
print(arr4 == arr5)

[[ True  True]
 [ True  True]]


In [ ]:
arr6 = np.array([1,2,3,4,5,1,2,1,1,1])
arr7 = np.array([1,1,1,2,3,4,2,4,3,3])
n = np.bincount(arr6).argmax()
print(n)
n2 = np.bincount(arr7).argmax()
print(n2)

In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
s = gfg.sum()
print(s)
rowsum = gfg.sum(axis=1)
print(rowsum)
col_sum = gfg.sum(axis=0)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [10]:
narray = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

diagonalsum = np.trace(narray)
diagonalsum
eigenval , _ = np.linalg.eig(narray)
_ , eigenval = np.linalg.eig(narray)
inverse_matrix = np.linalg.inv(narray)
determinant = np.linalg.det(narray)




In [11]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

product = np.dot(p, q)
print("Matrix Multiplication:\n", product)

Matrix Multiplication:
 [[16 19]
 [26 31]]


In [12]:
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])
innerproduct = np.inner(x,y)
outerpriduct = np.outer(x,y)
from itertools import product

cartesian = np.array([np.concatenate((a, b)) for a, b in product(x, y)])
print("Cartesian Product:\n", cartesian)


Cartesian Product:
 [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


que 2 Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row
(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [13]:
import numpy as np
from itertools import product

# -------------------- (a) PART --------------------

array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

print("Original Array:\n", array)


print("\n(a.i) Absolute Value:\n", np.abs(array))


print("\n(a.ii) Percentiles (Flattened):")
print("25th:", np.percentile(array, 25))
print("50th:", np.percentile(array, 50))
print("75th:", np.percentile(array, 75))

print("\nPercentiles (Column-wise):")
print("25th:", np.percentile(array, 25, axis=0))
print("50th:", np.percentile(array, 50, axis=0))
print("75th:", np.percentile(array, 75, axis=0))

print("\nPercentiles (Row-wise):")
print("25th:", np.percentile(array, 25, axis=1))
print("50th:", np.percentile(array, 50, axis=1))
print("75th:", np.percentile(array, 75, axis=1))

print("\n(a.iii) Mean, Median, Std (Flattened):")
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))

print("\nMean, Median, Std (Column-wise):")
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard Deviation:", np.std(array, axis=0))

print("\nMean, Median, Std (Row-wise):")
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard Deviation:", np.std(array, axis=1))

# -------------------- (b) PART --------------------

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("\n(b) Original Array:\n", a)

print("\nFloor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))


Original Array:
 [[ 1 -2  3]
 [-4  5 -6]]

(a.i) Absolute Value:
 [[1 2 3]
 [4 5 6]]

(a.ii) Percentiles (Flattened):
25th: -3.5
50th: -0.5
75th: 2.5

Percentiles (Column-wise):
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]

Percentiles (Row-wise):
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]

(a.iii) Mean, Median, Std (Flattened):
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median, Std (Column-wise):
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Mean, Median, Std (Row-wise):
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]

(b) Original Array:
 [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements
(b) For the array: array = i. Integer elements only
ii. Float elements only
np.array([10, 52, 62, 16, 16, 54, 453]), find
np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

In [14]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)
smallest_4 = np.sort(array)[:4]
print("4 smallest elements:", smallest_4)
largest_5 = np.sort(array)[-5:]
print("5 largest elements:", largest_5)


Sorted array: [ 10  16  16  52  54  62 453]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]
